[package]
name = "kube-discord-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.12", features = ["model"]}
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"]}
dotenv = "0.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"